module.exports = {
    verifyCollection: 'verifydata',
    userCollection: 'userdata',
    eventCollection: 'events',
    bookCollection: 'Eventbooking',
    fineCollection: 'fine',
    otCollection: 'ot',
    teCollection: 'te',
    withdrawCollection: 'withdraw',
    salaryCollection: 'salary',
    captainCollection: 'captain',
    notificationCollection: 'notification',
    eventdateCollection: 'eventdate',
    otpCollection: 'otp',
    imageCollection: 'images',
    proofCollection: 'proofs',
}